targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          build_extensions:
            '^lib/{{}}.dart': 'lib/widgets/{{}}.g.dart'
      custom_widget_generator|custom_widget_annotation:
        options:
          build_extensions:
            '^lib/{{}}.dart': 'lib/widgets/{{}}.g.dart'