targets:
  $default:
    builders:
      custom_widget_generator|custom_widget_annotation:
        options:
          build_extensions:
            '^lib/{{}}.dart': 'lib/widgets/{{}}.g.dart'
          enabled: true
      source_gen|combining_builder:
        options:
          build_extensions:
            '^lib/{{}}.dart': 'lib/widgets/{{}}.g.dart'

builders:
  custom_widget_annotation:
    target: ":custom_widget_generator"
    import: "package:custom_widget_generator/builder.dart"
    builder_factories: ["customWidgetBuilder"]
    build_extensions: {'^lib/{{}}.dart': ['lib/widgets/{{}}.g.part']}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]